services:
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        container_name: task_test_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./nginx/logs:/var/log/nginx/
            - ../:/var/www
        depends_on:
            - php
            - db
        links:
            - php
        environment:
            TZ: ${TIME_ZONE}
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: task_test_php
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ../:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - db
        environment:
            TZ: ${TIME_ZONE}
    db:
        build:
            context: .
            dockerfile: ./mysql/Dockerfile
        container_name: task_test_db
        restart: unless-stopped
        ports:
            - "33060:3306"
        volumes:
            - dbData:/var/lib/mysql
            - ./mysql/logs:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: ${TIME_ZONE}
volumes:
    dbData:
        driver: local
